[package]
name = "swp_logic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12.0"
hashbag = "0.1.11"
itertools = "0.10.5"
num = "0.4.0"
rulinalg="0.4.2"
rand = "0.8.5"